// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMxoHjumCpizSP9zaC9JWV6fy-uZs8vcM',
    appId: '1:514470355860:web:0919c65aadbbf901402581',
    messagingSenderId: '514470355860',
    projectId: 'sokka-2f2c6',
    authDomain: 'sokka-2f2c6.firebaseapp.com',
    databaseURL: 'https://sokka-2f2c6.firebaseio.com',
    storageBucket: 'sokka-2f2c6.appspot.com',
    measurementId: 'G-LDXWV18WE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg-MpH4N075Gbc0w18L5eL6hyJS1AV9vA',
    appId: '1:514470355860:android:a36b59af7b415901402581',
    messagingSenderId: '514470355860',
    projectId: 'sokka-2f2c6',
    databaseURL: 'https://sokka-2f2c6.firebaseio.com',
    storageBucket: 'sokka-2f2c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj1q4wabVbb4MHt8PDXq_X8bs848jutl4',
    appId: '1:514470355860:ios:a709b2cc4a3e095f402581',
    messagingSenderId: '514470355860',
    projectId: 'sokka-2f2c6',
    databaseURL: 'https://sokka-2f2c6.firebaseio.com',
    storageBucket: 'sokka-2f2c6.appspot.com',
    iosBundleId: 'com.sokkatech.myFirstApplication',
  );
}
